### ISSUE TITLE
NHS Number Python library collaboration

### ISSUE THREAD

**Issue by pacharanero** [Iain-S/nhs_number_generator#8]
Hi @Iain-S 

I am working with some of the other developers who have made some kind of NHS Number validator/generator  library in Python, of which there are several.

Would you be interested in collaboration with us to try and coalesce the best features and code of the many NHS Numbers libraries, and develop and maintain just **one**, well tested, well code-reviewed, performant and canonical library.

We have secured the support of the Faculty for Clinical Informatics in hosting the library in their GitHub organisation.

https://github.com/uk-fci/nhs-number

Let me know if interested in being involved.

Marcus Baw
Dr Marcus Baw
General Practitioner, Clinical Informatician, Software Developer.
Immediate Past Chair of Royal College of GPs Health Informatics Group.
phone: +44 7747 600617
twitter: [@marcus_baw](https://twitter.com/marcus_baw)
github: [pacharanero](https://github.com/pacharanero)

**Comment by Iain-S** [comment]
Hi Markus

Glad to hear that you are working on this topic. I like the summary of the different ranges and their intended uses you have put in your README.

If I was to work more on (or rewrite) this `nhs_number_generator` package then there are definitely some things I would add or do differently, e.g.

- Type hints are being increasingly used in Python and should be relatively easy to add
- I would put it on PyPI (as I see you have with `nhs-number`) 
- Python 2 support isn't really necessary and it is a pain to maintain
- It would have been nice to have someone else review the code, I'm sure there are bugs
- I would emphasise (as you have) that this is for generating test/dummy numbers rather than for use in production
- I might use [click](https://click.palletsprojects.com/en/8.1.x/) instead of argparse, though the latter comes as part of the standard library so `nhs_number_generator` has no dependencies.

However, I think there's a chance that you will fall foul of [this](https://xkcd.com/927/) xkcd. If you have the time and expertise to develop a package, I think it often benefits the community more to extend or improve the existing libraries rather than to add another option. Having said that, you are more than welcome (as per the GPL LICENSE) to take any code here that is of use to you and, while I don't have time to actively work on `nhs-number`, feel free to `@` me if there's something specific you would like my input on.

All the best

Iain

**Comment by pacharanero** [comment]
Thanks @Iain-S - agree with all your points. We are hoping to swerve the 'Standards' XKCD by basically adopting and building on one of the existing libraries and porting code into that as necessary. Aiming to keep the API simple and Pythonic.

If you get time to review, comment or if you want to raise Issues, the active project is now here https://github.com/uk-fci/nhs-number and once we have it up and usable then we would hopefully like as many other related libraries to signpost to it so we converge efforts on the one library.
